apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-fetcher-webserver
  namespace: {{.Values.namespace}}
spec:
  replicas: {{$.Values.replicaCount}}
  selector:
    matchLabels:
      app: zip-fetcher-webserver
  template:
    metadata:
      labels:
        app: zip-fetcher-webserver
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
      - name: webserver
        image: {{.Values.image.repository}}
        imagePullPolicy: Always

        command:
          - ./usr/bin/zip_fetcher
        ports:
        - containerPort: 8080
        env:
          - name: ZIP_FILE_LOCATION
            value: /uszips.csv


---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}

---
apiVersion: v1
kind: Service
metadata:
  name: zip-fetcher-webserver-svc
  namespace: {{.Values.namespace}}
  labels:
    app: zip-fetcher-webserver-svc
spec:
  selector:
    app: zip-fetcher-webserver
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{.Values.namespace}}
  name: zip-fetcher-ingress

spec:
  ingressClassName: "home-ingress-controller"
  rules:
    - host: "zip-api.baxterhome.net"
      http:
        paths:
          - backend:
              service:
                name: zip-fetcher-webserver-svc
                port:
                  number: 8080
            pathType: "Prefix"
            path: "/"
